# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ '3.8', '3.9', '3.10.0-rc.1' ]

#        services:
#            minio:
#                image: minio/minio:latest
#                ports:
#                    - 9000:9000
#                    - 9001:9001
#                env:
#                    MINIO_ROOT_USER: admin
#                    MINIO_ROOT_PASSWORD: adminadmin
#                    MINIO_DEFAULT_BUCKETS: ekko
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip poetry
                    poetry config virtualenvs.create false
                    poetry install --no-interaction

            -   name: Run minio
                run: |
                    docker run \
                        -d \
                        --rm \
                        --name minio \
                        -- network host \
                        -p 9000:9000 \
                        -p 9001:9001 \
                        -e MINIO_DEFAULT_BUCKETS=ekko \
                    minio/minio:latest server --console-address ":9001" /data

            -   name: Create bucket
                run: |
                    docker run --rm minio/mc mb ekko

            -   name: Lint with flake8
                run: |
                    flake8 ekko tests

            -   name: Lint with mypy
                run: |
                    mypy ekko/

            -   name: Lint with black
                run: |
                    black --check ekko tests

            -   name: Test with pytest
                run: |
                    pytest --no-cov-on-fail --cov ekko --cov tests

            -   name: Stop minio
                run: |
                    docker stop minio
                    docker rm minio
